### ISSUE TITLE
x64 With ACE Freezing

### ISSUE THREAD

**Issue by ilbinek** [michail-nikolaev/task-force-arma-3-radio#1226] opened 2017-03-24 15:51 UTC
**Arma 3 Version:*1.3.8* `` (stable)
**CBA Version:** `3.2.1` (stable / dev + commit hash)
**Task Force Radio Version:** `0.9.13` (armaholic release)

**Mods:**
- `@CBA_A3`
- `@task_force_radio
- http://withsix.com/p/Arma-3/collections/gJ5WzecQaUGt0DJiAN30Dg/c-s-e-c---addony-na-server (All of these)

**Description:**
- Games loads, freezes and stays freezed, whener you close it with TaskManager, error code - **0x00000001 – UNABLE_TO_INIT_DXGI**. _Which I believe is problem with **ACE**._ The old x32 version works. Problem is occured whenever the x64 version is started.

**Steps to reproduce:**
- Only start the game.

**Where did the issue occur?**
- Main menu, server browser, if you are fast enough.

**RPT log file:**
http://pastebin.com/21JrvCDy

Feel free to add me on steam /id/ilbinek for testing with these mods. Thanks for your work.

**Comment by dedmen** [comment] 2017-03-24 16:00
Arma version 1.3.8 doesn't exist.
TFAR version 0.9.13 doesn't exist.
If this is a ACE problem why are you reporting this to me?
Can't reproduce.

Invalid report. Closing.

**Closed by dedmen** 2017-03-24 16:00 UTC

**Comment by ilbinek** [comment] 2017-03-24 16:14
http://www.armaholic.com/page.php?id=23615 this is where 0.9.13 is written.
For the game versin, please accept my apologies. It is stable 1.68
Will report this problem to ACE devteam ;)

**Comment by dedmen** [comment] 2017-03-24 16:25
Apologies then. Didn't know about armaholic doing stuff I don't know anything about ^^
