### ISSUE TITLE
Talking problems with Zeus Remote Controlled units

### ISSUE THREAD

**Issue by Knight1981** [michail-nikolaev/task-force-arma-3-radio#1185] opened 2017-01-06 07:12 UTC
**Arma 3 Version:** `1.66` stable
**CBA Version:** `3.1.2.161105` stable
**Task Force Radio Version:** `0.9.12` stable

**Mods:**
- `@CBA_A3`
- `@task_force_radio
- `@ace3
- `@bwa3

**Description:**
If a Zeus controls a different unit via remote control and plays for example an civilian guy, we couldn't hear him talking (or very laggy talking). It seems that his voice is switching between the player and the remote unit.

In the release notes I found the hint, that you fixed "Fixed dead people could hear Zeus.". Maybe there is an error within this change, because in the last version it works fine. So we decided yesterday to downgrade to the previous version and we have no issues. Means I'm 100% sure the error is located within the latest version.

**Steps to reproduce:**
- Join dedicated server as a normal player
- Place an civilian guy
- Login into Zeus and remote control the civilian guy
- Go to another player and try to talk with him

You will see that he isn't able to hear you (or only some words very laggy). 

**Where did the issue occur?**
- Dedicated

**RPT log file:**
- ---

**Comment by dedmen** [comment] 2017-01-06 11:27
Duplicate of #1153
It is already Fixed in 1.0. 1.0 Pre-release is available and functional if your groups wants to test the beta.
1.0 should be feature complete in a month and will then go into more public Beta-testing.. And then if everything is fine we will fully release it.

**Comment by Knight1981** [comment] 2017-01-06 12:31
Thanks for the information, great! We will wait for the final (stable) version because the previous version still works fine for us.

**Comment by Knight1981** [comment] 2017-01-19 12:54
Sorry but where can I find the pre-release version? We urgently need this fixed because our Game Master isn't able to talk with us :-/

Thanks a lot.

**Comment by dedmen** [comment] 2017-01-19 14:39
https://github.com/michail-nikolaev/task-force-arma-3-radio/releases scroll down a bit.

**Comment by Knight1981** [comment] 2017-01-23 12:48
Thank you dedmen! I will test this version.

**Comment by Knight1981** [comment] 2017-01-23 16:28
I have tried the latest one but it doesn't work. We updated the mod and TS plugin, added the optional pbo to the addon folder but we couldn't hear each other talking / radio :-(

**Comment by dedmen** [comment] 2017-01-23 21:10
Why don't you keep using 0.9.8 as you said 2 weeks ago?
None of my beta testers reported any problem on build 194 yet.
Are you sure everyone has the same and latest plugin and Mod version?
Teamspeak seems to sometimes bug lout and not tell the plugin when the player switched channels or stuff. I don't know why yet because i couldn't reproduce it. Reloading the plugin while in the channel with all the other players should fix that.. If that is really the issue.

**Comment by Knight1981** [comment] 2017-01-24 07:22
0.9.8 doesn't work anymore with the newest Teamspeak 3 Client :( Thats why we had to use the 0.9.12 which has the Bug with Zeus controlled units.

Yesterday we installed 1.-1.0.194 (also on our dedicated server) and updated the TFAR Teamspeak Plugin on our clients. We joint our server and we were not able to hear each other talking :( Don't know why, sorry.

**Comment by dedmen** [comment] 2017-01-24 18:41
0.9.8 works just fine with the newest Teamspeak Client.. You just have to use the 0.9.12 Plugin. Nothing changed in the Plugin->Game Interface.

**Comment by Knight1981** [comment] 2017-02-26 16:34
Yesterday we've tested the new 1.0-PreRelease-1.0-dev.214 version. The problem with Zeus is fixed and the ability that the KI can hear us talking is really awesome! Very good work! But we had to many other bugs with this version so we can not use it at the moment :(

For example the vehicle radio doesn't work when speakers are enabled (only works with headphones). 
And after we rolled out 3km out of our base we were not longer able to use the radio. The quality was to bad and it sounded like we were some miles away from each other but we were all together in a compound. That was a bit strange that our radio works only in our base and not when we were outside in the middle of the map :-/ Hope you can find and fix these issues. Cheers!

**Comment by Knight1981** [comment] 2017-04-10 07:46
You can close this issue here. This is already solved. Only the problem with vehicle speakers exists. I created a new bugticket for that here:
https://github.com/michail-nikolaev/task-force-arma-3-radio/issues/1241

**Closed** 2017-04-10 23:05 UTC
