### ISSUE TITLE
Vehicle Intercom

### ISSUE THREAD

**Issue by Saborknight** [michail-nikolaev/task-force-arma-3-radio#1119] opened 2016-09-20 09:57 UTC
Hi, 
Whilst flying in a Heli Crew, or Riding in a vehicle crew of any sort, it would be awesome if there was a closed intercom system for players in the same vehicle.

When flying the rotors can be so loud that direct speech is very difficult to make out, however using radios allows the players to hear each other perfectly. However, when flying in formation, then using said radios would mean the crew of another vehicle also being able to hear your crew members.

I'd like to suggest that upon the crew members entering their vehicle slots, any direct speech be duplicated to a closed intercom between only other crew members (AKA you hear the voice directly as well as on a radio transmission and you can send transmission without keybindings)

For a pilot (which is my main role in my community) this would be a lifesaver in terms of hearing other crew members clearly without 1. having to sacrifice immersion by lowering your Environment Sounds level or 2. Having to sacrifice my ears by increasing the Teamspeak volumes or 3. Having to use an extra radio channel as alt to communicate with crew (which uses up an unnecessary freq and the ability for having a different alt.

I shall try my hand at implementing this in my own fork however I'm making this enhancement request in the very likely event that I fail.

Thanks, 
Arend

**Comment by kavinsky** [comment] 2016-09-20 10:17
Duplicate of #974

**Closed by kavinsky** 2016-09-20 10:17 UTC
