### ISSUE TITLE
A possibility to hear direct speech as a spectator

### ISSUE THREAD

**Issue by drawpause** [michail-nikolaev/task-force-arma-3-radio#1108] opened 2016-09-15 12:22 UTC
As per in ACRE. Please see the last minutes of this video for an example: https://www.youtube.com/watch?v=_N6_Ij-pEIY

**Comment by Davanseth** [comment] 2016-09-16 06:56
I second this. Would make TFAR just perfect.

**Comment by kavinsky** [comment] 2016-09-16 11:53
Duplicate of #861

**Closed by kavinsky** 2016-09-16 11:53 UTC
Labels: duplicate
