### ISSUE TITLE
Link between TS and Arma broken?

### ISSUE THREAD

**Issue by yurivw** [michail-nikolaev/task-force-arma-3-radio#1289] opened 2017-07-22 20:27 UTC
**Arma 3 Version:** `1.72` (stable)
**CBA Version:** `3.4.0` (stable)
**Task Force Radio Version:** `0.9.12` (stable)

**Mods:**
- `@CBA_A3`
- `@task_force_radio

**Description:**
- When joining a server I am not moved to the TFR room. On Teamspeak it gives me the following line of the plugin: `Task Force Radio Status (0.9.12):Connected N Play N P:0.9.12 A:`
I'm assuming the game doesn't communicate with Teamspeak somehow. 

**Steps to reproduce:**
- N/A

**Where did the issue occur?**
- All servers I join, some self-hosted, some hosted by friends and even a dedicated.

**RPT log file:**
- TO BE ADDED

**Comment by dedmen** [comment] 2017-07-22 21:04
Running Teamspeak and Game as Admin?

**Comment by yurivw** [comment] 2017-07-22 21:22
Yeah, I am.

**Comment by dedmen** [comment] 2017-07-23 10:09
Tried running one or both without Admin? Disable Antivirus maybe.

**Comment by yurivw** [comment] 2017-07-23 11:42
That didn't fix it either. There seems to be a lot of people out there with this problem, and they fixed it... But all posts just end with a thank you and how they did it themselves. Nobody is actually giving a solution.

Why is everyone so cryptic about this problem...

**Comment by dedmen** [comment] 2017-07-24 13:05
Because the Problem is very cryptic. The Problem lies inside Windows not in TFAR itself.
Sometimes a PC restart fixes it. Very often running as Admin fixes it. Sometimes nothing fixes it. 
That's why I replaced that system in TFAR 1.0 and it will be much more reliable in the future.

**Comment by dedmen** [comment] 2018-03-12 15:19
0.9.12 known problem. Fixed in 1.0.

**Closed by dedmen** 2018-03-12 15:19 UTC
