### ISSUE TITLE
arma3 1.42 / CBA RC6 compatibility

### ISSUE THREAD

**Issue by havena** [michail-nikolaev/task-force-arma-3-radio#924] opened 2015-04-09 18:08 UTC
The RC6 version of CBA will modify [Keybind system](http://feedback.altisrp.fr/file_download.php?file_id=6&type=bug&show_inline=1&file_show_inline_token=201504091625a54765b0895d59982014e3eaa021864df6f1).

> **Changelog:**
> * Keybind supports keyup
> * New keybind API CBA_fnc_addKeybind.sqf
> * Keybind support for ACER keyboards.
> * Keybind optimizations. PerFrameHandler support. Must faster.
> * Keybind improved localization support.
> * The old keybinds will revert to their defaults
> * These old keybinds defaults will be locked and cannot be changed.
> * So they will work however there will be warnings in the RPT to change to the new API so players can change their keys.
> * EH FireBIS fixes
> * String Functions Optimizations. Much faster.
> * Fixed RPT Errors with Updating Base Class and Cannot Delete....
> * Improved Hashes
> * XEH Support for "ReammoBox_F" enabled.
> * Improved Strings Functions with added Private declarations
> * Fixed the inability to return to default keybinds after starting a new mission.
> * Caching Changes. Ask Nou.
> * ADDED holdkey feature for Keybinds. - Nou
> * FIXED Arma 3 v1.42 RC Issue - Updating Base Classes
> * FIXED Arma 3 v1.42 RC Issue - fn_undefCheck.sqf not found
*>  ADDED CBA Debug Enhancement

**Comment by jonpas** [comment] 2015-04-09 18:14
Duplicate of #919

**Comment by havena** [comment] 2015-04-09 22:49
sry i dont see commit. thx

**Closed** 2015-04-10 07:59 UTC
Labels: duplicate
