### ISSUE TITLE
Needing to press radio buttons twice to actually transmit

### ISSUE THREAD

**Issue by sonst-was** [michail-nikolaev/task-force-arma-3-radio#1256] opened 2017-05-10 13:35 UTC
**Arma 3 Version:** `1.68.141205` (stable / rc / dev)
**CBA Version:** `3.2.1` (stable / dev + commit hash)
**Task Force Radio Version:** `0.9.12` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@task_force_radio`
- `@ace`
- `@acex`
- `@aresmodachillesexpansion`
- `@asr_ai3`
- `@cup_terrains`
- `@hiddenidentitypackv2`
- `@namalsk`
- `@rhsafrf`
- `@rhsgref`
- `@rhssaf`
- `@rhsusaf`
- `@tacticalbeards`
- `@xcam_taunus`

**Description:**
I have to press my SR and LR radio buttons always twice, otherwise nothing is sent over the radio. My SR key is `Tab`and my LR key is `F8` and I have both buttons on my mouse for easier access. While playing and trying to use SR or LR I have to press and release the buttons twice because otherwise nothing is sent. When I press the button only once I'll get the notification that I'm transmitting but no one receives my transmission.

**Steps to reproduce:**
Start playing and try to radio someone by pressing and holding the radio button.

**Where did the issue occur?**
- Dedicated

**RPT log file:**
[arma3_x64_2017-05-03_19-59-33.txt](https://github.com/michail-nikolaev/task-force-arma-3-radio/files/989903/arma3_x64_2017-05-03_19-59-33.txt)

**Comment by dedmen** [comment] 2017-05-10 17:14
You have way more Problems than just TFAR with that 2.5MB RPT...
Can you reproduce it with only the following mods?

- @CBA_A3
- @task_force_radio
- `@ace`
- `@acex`
- @cup_terrains
- @rhsafrf
- @rhsgref
- @rhssaf
- @rhsusaf

**Comment by DerZade** [comment] 2017-05-11 12:10
I can confirm this issue. I have experienced this since I use TFAR - at least I can't remember not having it - with various modsets and TFAR versions.

**Comment by dedmen** [comment] 2017-05-11 12:12
I know that LR can make problems when you use a hotkey without a modifier. shouldn't happen with SR though.
Also I reworked the Hotkey handler in 1.0 and CBA is also rewriting their hotkey system. Quite possibly that will fix your bug. If not we will investigate it further after the CBA update is out.

**Comment by DerZade** [comment] 2017-05-11 13:57
After thinking and watching some recordings I have to agree, that there is only a problem with the LR.
Pressing LR Transmit but it's first transmitting on the SR, only after pressing LR Transmit again, it switches to LR.

**Comment by dedmen** [comment] 2017-05-11 14:53
Oh yeah.. That can be fixed by either adding a modifier (STRG, ALT, SHIFT) to the hotkey.
And also fixed in 1.0.

**Comment by sonst-was** [comment] 2017-05-12 16:00
> Pressing 'LR Transmit' but it's first transmitting on the SR, only after pressing 'LR Transmit' again, it switches to LR.

I never thought of it, but my squad quite often said my should've-been-LR transmission where instead SR transmission. 

I'll add an modifier and report back soon.

**Comment by dedmen** [comment] 2017-09-18 08:57
Fixed in 1.0 so I'll close this.

**Closed by dedmen** 2017-09-18 08:57 UTC
