### ISSUE TITLE
1.62 Menu Broken

### ISSUE THREAD

**Issue by Slowrider8** [michail-nikolaev/task-force-arma-3-radio#1085] opened 2016-07-14 16:18 UTC
Ever since the new main menu was available TFAR has been causing big problems with it. Several menu elements are not clickable without hovering over the corner, there are menu elements just thrown around randomly and some people have not been able to click any buttons on the menu at all (can't get to options, editor, anything)

**Comment by ArMaTeC** [comment] 2016-07-14 16:43
the recent CBA update fixed the text hovering over it so not 100% if its TFAR or CBA that's the cause of this

**Comment by Slowrider8** [comment] 2016-07-14 17:00
Although I haven't been experiencing the drop-down menu buttons not working other people I know have. However, I still cannot press the left and middle boxes, and can only click the right box by hovering in the bottom right corner. This is with just TFAR and CBA. TFAR also messes with other mods that use menu elements even if they were fixed. For example ACE3.
**CBA + ACE** (Working Normally)
![20160714175310_1](https://cloud.githubusercontent.com/assets/1593099/16848174/607eebb2-49ec-11e6-9ed3-9b650624e77d.jpg)
**CBA + ACE + TFAR** (Note missing elements at bottom and ACE Options tab at top)
![20160714175403_1](https://cloud.githubusercontent.com/assets/1593099/16848180/67c1bec2-49ec-11e6-9786-5bd440075748.jpg)
**CBA + TFAR** (Note INTEL/News element)
![20160714175436_1](https://cloud.githubusercontent.com/assets/1593099/16848183/6db363ee-49ec-11e6-920a-8825de03f5e6.jpg)

**Comment by Armilio** [comment] 2016-07-14 18:56
I can confirm that it's TFR.

**Comment by michail-nikolaev** [comment] 2016-07-14 20:06
fixed in update

**Closed by michail-nikolaev** 2016-07-14 20:06 UTC
