### ISSUE TITLE
Feature Request - Transmitter/Communication towers that sender boost range

### ISSUE THREAD

**Issue by Radeni** [michail-nikolaev/task-force-arma-3-radio#1232] opened 2017-03-31 00:04 UTC
One thing most of the military bases have are Transmitter towers for long range communications. Even vanilla Arma has a lot of these objects and it would be a great deal if they could be put to use.
![20170331013156_1](https://cloud.githubusercontent.com/assets/16863311/24530442/308016b0-15b2-11e7-96e7-40d5497f4340.jpg)
The idea is to have an object (static or even a vehicle) that would have a boosting range. If the sender is in the range of the object then the transmission range would increase. A good idea would be to have these boosters hackable. That way the range boost could be limited to the last side that has hacked the tower and hacking could be done with a timed action (Such as vanilla BIS revive or vanilla UAV hacking) and if the unit hacking it has a toolkit or is an engineer they would have a speed boost.
All these things things could be managed with a couple of modules. 1 module for settings such as require engineer to hack, require toolkit, time required to hack,engineer speed bost multiplier,etc. Another module for turning objects into transmission boosters by syncing them which would also allow turning vehicles into boosters. The module could have settings such as: Side,sender boost range, distance required for boost, if its hackable or not,etc. 

I hope this is all possible to code into what you already have and if so i really hope that you like my feature idea. Hacking and destroying radio towers and vehicles would get a whole new meaning

**Comment by dedmen** [comment] 2017-03-31 13:26
I think hacking stuff is a bit out of scope for TFAR. It would be better suited in an external Addon.

**Comment by Radeni** [comment] 2017-03-31 13:39
what i meant by hacking is getting something that has no side,or is on enemy's side to be yours. My idea was to have it as an optional module where you'd enable or disable hacking globally and it could be included in main addon but disabled by default

**Comment by dedmen** [comment] 2017-03-31 13:50
Hacking is a lot of code. And currently Radio towers are not on any Side. Which I will consider adding for 1.1.
As I said Hacking itself will not be in TFAR itself. But I will add the backend stuff that an external Addon could not add.

**Comment by Radeni** [comment] 2017-03-31 14:06
Oh cool. does that mean it will boost transmission of any sender in the radius?

**Comment by dedmen** [comment] 2017-03-31 16:11
Yes... That's already implemented.

**Comment by Pergor** [comment] 2017-04-05 10:11
I once made a script to give a vehicle or an object of type Land_DataTerminal_01_F the ability to boost radio range for a certain side, depending on certain conditions.
It hasn't been updated for tfar 1.0 yet, but I'll certainly do that in the next couple days or weeks. You might want to take a look at it if you'd like to do something like that by yourself or use it alltogether:
https://github.com/Pergor/ADV_MissionTemplate/blob/master/adv_missiontemplate.altis/functions/shared/fn_radioRelay.sqf

**Comment by dedmen** [comment] 2018-03-12 15:33
@Pergor Your script can be redone using the TFAR 1.0 relay towers. One problem is that they don't only boost nearby radios. But every radio that's sending range reaches the tower. 
Do you think we need a relay tower with limited receiving range on the tower? Although that's kinda unrealistic.

**Comment by Pergor** [comment] 2018-03-13 10:22
That sounds great.
I would consider the maximum range to be something of a compromise between realism and expected map size anyway.

**Comment by dedmen** [comment] 2018-03-13 12:04
The problem is that most "boost" scripts only boost the range of radios nearby. Like 50m away or less. Which is completely unrealistic as it could boost any radio that is in range. As that radio's signal can reach the booster. And the radio signal reaches several kilometers and not just 50m.
So you think that's useful or should people rather just be forced to use the realistic and logical way?

**Comment by Pergor** [comment] 2018-03-13 16:55
Yeah, 50m is far to little a range for the radio towers to be considered 'realistic'. It's just from a gameplay point of view that some form of limitation should be in place as to not overpower the radio towers.
If a radio tower is in transmitting range of a radio, it should pick up the radio's signal and boost it to its own transmitting range, that's a given. Handheld radios have a lower transmitting range, so you have to be closer to a radio tower for it to pick up your signal - supposedly you wouldn't even need a 'receiving range' from the radio tower then. The opposite would be true for backpack or aircraft radios. They have a much larger range and therefore could be further away to still be picked up by the radio towers. The 'receiving range' from the towers could possibly be limitless, since it's more depending on the transmitting range of the radio that tries to get its signal to the tower.
The transmitting range should probably not reproduce real-world behaviour as well. With the right equipment (and atmospherical factors in play) you could use a regular household antenna to transmit quite some distance, in fact much larger distances than any Arma map has ever achieved.

So, to put it in Arma terms:
if ( (radio distance tower) < tf_range(RADIO) ) then { tf_range(RADIO) = tf_range(TOWER) };
That way only tf_range(RADIO) matters, depending on it being 2k, 5k, 20k or 40k. tf_range(TOWER) should only matter in regard to the boosted range.

**Comment by dedmen** [comment] 2018-03-13 17:30
You just explained how it currently works.

**Comment by Pergor** [comment] 2018-03-14 02:36
Then it's more than enough. :)

**Comment by dedmen** [comment] 2018-03-14 08:27
:+1:

**Closed by dedmen** 2018-03-14 08:27 UTC
