### ISSUE TITLE
Add support to Mumble

### ISSUE THREAD

**Issue by kavinsky** [michail-nikolaev/task-force-arma-3-radio#528] opened 2014-04-16 23:39 UTC
http://forums.bistudio.com/showthread.php?169029-Task-Force-Arrowhead-Radio&p=2669249&viewfull=1#post2669249

Check that thread and the next.

Project Reality has a good implementation.

**Comment by Krzmbrzl** [comment] 2019-08-13 15:05
This seems like a duplicate of #312 to me

**Comment by dedmen** [comment] 2019-08-14 08:40
Correct. We'll continue in #312

**Closed by dedmen** 2019-08-14 08:40 UTC
