### ISSUE TITLE
Can't set up frequencies via script for opfor on dedicated.

### ISSUE THREAD

**Issue by AtomMrav** [michail-nikolaev/task-force-arma-3-radio#1058] opened 2016-05-12 01:49 UTC
I have problem setting up frequencies via init.sqf script for opfor units. Everything works fine on local host, but on dedicated it works only for blufor, but opfor is getting random generated frequencies.
I have tried couple different scripts, and i get same result. On local host it work both for blufor and opfor, but on dedicated it works only for blufor.

I used the following scripts:

[Script 1](http://pastebin.com/8fMF4XFM)
[Script 2](http://pastebin.com/bFd2KuQn)
[Script 3](http://pastebin.com/Mp8VeRws)

Please, can someone help me? What am I doing wrong?

**Comment by ozdeadmeat** [comment] 2016-05-13 14:22
Yep, I am experiencing the exact same issues here. My Code

player setVariable ["tf_receivingDistanceMultiplicator", 6];
player setVariable ["tf_sendingDistanceMultiplicator", 6];
TF_give_microdagr_to_soldier = false;
tf_no_auto_long_range_radio = true;
tf_same_sw_frequencies_for_side = true;
tf_same_lr_frequencies_for_side = true;
TF_give_personal_radio_to_regular_soldier = false;
TF_terrain_interception_coefficient = 5.0;
tf_freq_west = [0,7,["38.8","69.9","78.5","104.7","311","404.5","411","488.6","500.5"],0,"BoTM_W_SR",-1,0,"",false];
tf_freq_west_lr = [0,7,["41","78.2","67.9","77.4","84.7","68.7","48.7","66.7","49","67.6"],0,"BoTM_W_LR",-1,0,false];

**Comment by michail-nikolaev** [comment] 2016-05-22 17:23
Hm... Could you test fo GUER please?

**Comment by dedmen** [comment] 2016-09-19 03:13
@ozdeadmeat 
Script 1 line 15-18 dont match array syntax from https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/arma3/%40task_force_radio/addons/task_force_radio/functions/fn_generateLrSettings.sqf#L26

Script 2 doesnt do publicVariable

**Comment by dedmen** [comment] 2016-09-19 03:24
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/arma3/@task_force_radio/addons/task_force_radio/functions/fn_getLrSettings.sqf#L94
What is that + doing there? May that create a script error? so it doesnt set the values?

**Comment by CorruptedHeart** [comment] 2016-09-19 05:12
I believe the `+` is there to cause the array to be copied instead of simply referenced. I'm not 100% sure why though.

**Comment by dedmen** [comment] 2016-09-19 06:18
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/arma3/@task_force_radio/addons/task_force_radio/functions/fn_setLrSettings.sqf does another copy... I understand the copy on setVariable but not the other one.
@kavinsky we need some task list for such small tasks. Dont want to create an issue for that everytime.

**Comment by Xawery94** [comment] 2016-12-22 12:04
The problem is still here. I can't set up frequencies for all side on dedicated server, on local server it's working well but on dedicated server the frequencies doesn't set up at all. I was using 0.9.12 version of TFAR.

**Comment by tiapfy** [comment] 2017-10-06 12:44
Still having this problem, I'm forced to use tfar 0.9.8 to use scripts like this:
_if ((isServer) or (isDedicated)) then { 
    tf_no_auto_long_range_radio = true; 
    publicVariable "tf_no_auto_long_range_radio"; 
    tf_same_sw_frequencies_for_side = true; 
    publicVariable "tf_same_sw_frequencies_for_side"; 
    tf_same_lr_frequencies_for_side = true; 
    publicVariable "tf_same_lr_frequencies_for_side"; 

    _settingsSwGuer = false call TFAR_fnc_generateSwSettings; 
    _settingsSwGuer set [2, ["311","312","313","314","315","316","317","318"]]; 
    tf_freq_guer = _settingsSwGuer; 

     _settingsLrGuer = false call TFAR_fnc_generateLrSettings; 
     _settingsLrGuer set [2, ["50","51","52","53","54","55","56","57","58"]]; 
     tf_freq_guer_lr = _settingsLrGuer; 

    _settingsSwWest = false call TFAR_fnc_generateSwSettings; 
    _settingsSwWest set [2, ["311","312","313","314","315","316","317","318"]]; 
    tf_freq_west = _settingsSwWest; 

     _settingsLrWest = false call TFAR_fnc_generateLrSettings; 
     _settingsLrWest set [2, ["50","41","42","43","44","45","46","47","48"]]; 
     tf_freq_west_lr = _settingsLrWest; 
     
     
       _settingsSwEast = false call TFAR_fnc_generateSwSettings; 
    _settingsSwEast set [2, ["311","312","313","314","315","316","317","318"]]; 
    tf_freq_east = _settingsSwEast; 

     _settingsLrEast = false call TFAR_fnc_generateLrSettings; 
     _settingsLrEast set [2, ["50","41","42","43","44","45","46","47","48"]]; 
     tf_freq_east_lr = _settingsLrEast; 
     
     


};_

**Comment by dedmen** [comment] 2017-10-06 21:37
@tiapfy 0.9.8 is outdated. And there is a module in the editor to set default frequencies.

**Comment by tiapfy** [comment] 2017-10-07 10:58
Oh, sorry then, my bad.

**Comment by dedmen** [comment] 2019-06-04 08:07
Probably fixed in 1.0
Just open a new bug report if you can reproduce in 1.0

**Closed by dedmen** 2019-06-04 08:07 UTC
Labels: bug, info needed
