### ISSUE TITLE
TFAR default radio assigns faction default

### ISSUE THREAD

**Issue by specop0** [michail-nikolaev/task-force-arma-3-radio#1212] opened 2017-03-04 11:55 UTC
**Arma 3 Version:** stable
**CBA Version:** `3.1.2` (stable)
**Task Force Radio Version:** `1.0-rc209` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@task_force_radio`

**Description:**
On mission start and at respawn TFAR assigns the faction default radio. Not a custom one assigned via onPlayerRespawn.sqf

**Steps to reproduce:**
- Host attached mission on dedicated server
- At mission start: fadak is assigned
- At respawn: fadak is assigned
- At manually applying the loadout (addAction): anprc152 or pnr1000a is assigned

**Where did the issue occur?**
- Dedicated Multiplayer
- It does not occur at Self-Hosted Multiplayer

**Example mission:**
[tfar-default-radio.VR.zip](https://github.com/michail-nikolaev/task-force-arma-3-radio/files/818602/tfar-default-radio.VR.zip)

**Comment by dedmen** [comment] 2017-03-06 16:25
Reproduced
Server
```
16:49:44:741130 "TFAR_RadioRequestEvent [[""TFAR_fadak""],O Alpha 1-1:1 (dedmen) REMOTE] 182.135"
16:49:44:741702 "Send TFAR_RadioRequestResponseEvent [""TFAR_fadak_1""] 182.136"
```
Client:
```
16:49:43 ["TFAR_SendRadioRequest",["TFAR_fadak"]]
16:49:44 ["onPlayerRespawn.sqf"]
16:49:44 ["give 152"]
16:49:44 ["onPlayerRespawn.sqf done"]
16:49:46 ["TFAR_ReceiveRadioRequestResponse",["TFAR_fadak_1"]]
```
Your Loadout script is executing in exactly the wrong time.... This is probably because of the performance Improvement in the Radio request system :/ I think I will just delay that by a couple seconds after missionStart...



Fixed in b215
The radio request script should only run 5 seconds after respawn. But TFAR's onRespawn handler would execute it immediatly. Thanks for the report and the nice repro mission.

**Closed by dedmen** 2017-03-06 16:25 UTC
