### ISSUE TITLE
TAB for LR works incorrect

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#937] opened 2015-04-20 21:54 UTC
http://forums.bistudio.com/showthread.php?169029-Task-Force-Arrowhead-Radio&p=2923581#post2923581

**Comment by GRUBES** [comment] 2015-05-14 07:39
Able to reproduce this with any key, not just Tab. I rebound "LR Transmit" keybinding to several keys like "C" and still see this issue.

**Comment by GRUBES** [comment] 2015-05-15 05:15
Duplicate of #845 ?

**Comment by dedmen** [comment] 2016-09-19 06:41
Forum link not valid anymore

**Comment by BmanDesignsCanada** [comment] 2017-05-29 10:05
I am not able to reproduce this in `1.-1.0.244`
Both Tab and "C" work fine

**Comment by dedmen** [comment] 2017-05-29 11:31
Yes. Was fixed in  cecc67d3ef46cf125827b48b541448fdfbb1f60

**Closed by dedmen** 2017-05-29 11:31 UTC
Labels: bug
