### ISSUE TITLE
Audio Issue on TaskForceRadio Channel

### ISSUE THREAD

**Issue by pablodma** [michail-nikolaev/task-force-arma-3-radio#1386] opened 2018-02-11 20:23 UTC
**Arma 3 Version:** `1.80` (stable)
**CBA Version:** `3.5` (stable)
**Task Force Radio Version:** `0.9.12 (stable) & 1.0-dev.274` (PreRelease)

**Mods:**
```
- @CBA_A3
- @task_force_radio
```
**Description:**
First letters of a word are not heard if the user is using "voice activation detection" for voice capture on TeamSpeak 3. No matter how sensitive the voice activation slider is set up. This does not happen with ACRE, because it doesn't mute clients if they are close enough to speak to each other without using the radio. TFAR mutes clients by default on TS3 and un-mutes them when they want to speak, thus generating the issue at hand. 

TeamSpeak won't transmit the first syllable of a word i.e.: When player 1 says: "Ten-Four" player 2 will hear: "n-Four"

**Steps to reproduce:**
- Enable Voice Activation on teamspeak
- Create TaksForceRadio Channel on Teamspeak (Make sure that the right channel is configured in the module)
- Count to 10 slowly, to let the microphone voice detection deactivate and activate between each number.
- The user will heard "..en" instead of "ten" or "..our" insted of "..four"

**Where did the issue occur?**
- Dedicated & Self-Hosted Multiplayer & Editor (Multiplayer)

**Video**
https://drive.google.com/open?id=1g5QD_U9WIwTwvD5SzJIgUlTfd5UGFQD6

**RPT log file:**
Local:
- https://pastebin.com/Gh5A8UcJ

Dedicated
- https://pastebin.com/qSvjYwMv

**Comment by dedmen** [comment] 2018-02-12 07:06
When you start to talk, Teamspeak sends a message to everyone telling them to unmute the talking user.
I guess it could be possible that the message arrives after the first audio packet. Though no one reported that so far.

**Comment by pablodma** [comment] 2018-02-12 13:02
Hi Dedmen, thanks on youy quick response. 
Unfortunatly, ive just downloaded and tried 1.0-PreRelease-1.0-dev.274, and this behaviuor stills
happens. 
Were you able to reproduce this bug? Is something missing/worng on our side? 
Thanks 
Pablo

**Comment by dedmen** [comment] 2018-02-12 15:03
We couldn't reproduce it so far. What is you ping in TS like?
Can you make a `/tfar full` log dump next time that happens?
Create the issue a couple times. Shortly after that write `/tfar full` in Teamspeak chat and send it. It will give you back a path to the log. Just put that in a zip and upload it here.  
Best if you could test it with as little people in the channel as possible.

**Comment by pablodma** [comment] 2018-02-12 16:01
Our TS3 server is currently located in Canada, and we have around 190ms of ping. (Location of our players is near south america). 
So, taking account of this situation, we've just tried with a TS3 self-hosted, with 16ms of ping and it works fine. 

We understand now that this behaviour may not be an issue o bug right now, but it will be great if your team consider the chance of taking any action on this situation. 
Not all arma 3 comunities have the resources to host their TS3 servers on their own countries

Being a comunity based in shouth america, and given that we are a community based in south america, the are little to no businesses that give these kind of services reliably and at a reasonable price, say dedicated servers or ArmA 3 servers, etc. Thus we choose to host our services abroad, because it's not cheaper but more reliable.

In your experience, do you see any chance to review this scenario?

Anyways, we will be uploading the log dump of TS3 in the next hours
Thanks!

**Comment by dedmen** [comment] 2018-02-12 17:50
I don't know how I would fix this. The muting is done to preserve bandwidth. Unmuting just in case someone might be talking makes the muting completly useless.
I have to know if someone does actually intent to talk. And if I only know so late that the first audio packet is cut off then that's how it is.

**Comment by pablodma** [comment] 2018-02-12 18:47
Maybe you could fix this with something similar to ACRE system?. It doesn't mute clients if they are close enough to speak to each other without using the radio, and it mute them when they begining to separate form each other. 
It's just and idea or suggestion

**Comment by dedmen** [comment] 2018-02-12 18:50
Isn't TFAR already doing that?
... Yes it is 
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/1.0/ts/src/plugin.cpp#L87

**Comment by pablodma** [comment] 2018-02-12 19:25
We've just tested the following: In spite of being one player standing next to the other TeamSpeak 3 still mutes the player if he is not talking. Attached you can find the /tfar full log dump. We look forward to getting this resolved, as it would be beneficial to more than a handful of people.
If you need any more help let us know

Here's a video of our test.
https://drive.google.com/file/d/13xvhcMAemfT2PsBrEfGQSv6PoO4_K31P/view?usp=sharing

[12-02_16-12-36.zip](https://github.com/michail-nikolaev/task-force-arma-3-radio/files/1717443/12-02_16-12-36.zip)

**Comment by dedmen** [comment] 2018-02-13 08:38
#TODO remove !isTalk check in `setGameClientMuteStatus`.
But some check for amount of near players would be good. We don't want to have 60 unmuted guys standing around us. Although that doesn't really matter as they would get unmuted anyway if they talked. And if they don't talk they don't cause any traffic.
So just removing the isTalk check should be enough.

**Comment by pablodma** [comment] 2018-02-13 17:30
Sure! no problem. we will be uploading a new video and the log dump within the next 3/4 hours, in case you need them.
Do yo have an aprox. Release date for a Dev with this enhacement?
Thanks!

**Comment by dedmen** [comment] 2018-02-13 18:23
dev builds are paused till I get further with the "cannot hear someone" bug. The next build should include it.

**Comment by dedmen** [comment] 2018-02-14 11:12
Fix will be in build 276. Will close this after you or someone else confirmed it working.

**Comment by pablodma** [comment] 2018-02-14 15:14
Great! If you want us to test anything before build 276, just let us know. 
Thank you!

**Comment by dedmen** [comment] 2018-04-12 12:44
276 is out now. Took a little...

**Comment by dedmen** [comment] 2018-07-04 12:47
I just assume it's working. Just comment if it isn't.

**Closed by dedmen** 2018-07-04 12:47 UTC
Labels: enhancement, teamspeak
