### ISSUE TITLE
TFAR change textures of Armed Offroad vehicles

### ISSUE THREAD

**Issue by CC-KRONUS** [michail-nikolaev/task-force-arma-3-radio#1190] opened 2017-01-16 11:52 UTC
Arma 3 
CBA Version: 3.1.2
Task Force Radio Version: 0.3.12

Mods:
@CBA_A3
@task_force_radio

Description:
TFAR change textures of B_G_Offroad_01_armed_F  and O_G_Offroad_01_armed_F 

Steps to reproduce:
Load Arma+CBA 3.1.2
- Go to editor
- Place one or both of B_G_Offroad_01_armed_F  and O_G_Offroad_01_armed_F   (Armed cammo offroad used by guerrilla)
- Observe that the vehicle is available in Camo and going to "edit vehicle appearance" will allow to select specific camo pattern.

Now:

- Reload game with Arma + CBA 3.1.2 + TFAR 0.3.12
- Place one or both of B_G_Offroad_01_armed_F  and O_G_Offroad_01_armed_F .  Vehicle is only spawned in red color.  in "edit vehicle appearance" no longer show options to change texture.

**Where did the issue occur?**
ed3n editor

This matter has been noticed by other users

https://www.reddit.com/r/arma/comments/5mjmlm/armed_off_road_only_spawns_in_red/
https://epochmod.com/forum/topic/37557-armed-offroad-only-available-in-red/

**Comment by dedmen** [comment] 2017-01-16 16:29
#827
I don't really know what thats caused by
We are adding Isolation and hasLRRadio variables to Offroad_01_armed_base_F But We aren't doing anything more.. Well I see a dependency missing inside RequiredAddons.. I'll try to add that..
Thank you very much.. you are the first one to provide steps to reproduce on that issue.

**Comment by dedmen** [comment] 2017-01-16 17:41
Found it!
Blame 5348b65d5e0713785874e22991e23595fe472ab5
He had class `Offroad_01_armed_base_F:Offroad_01_base_f` But it should be class `Offroad_01_armed_base_F:Offroad_01_military_base_F` Maybe it changed in an arma update

**Comment by dedmen** [comment] 2017-01-16 17:52
Confirmed Fix. Thanks for the report.
Will be in Pre-release 169

**Closed by dedmen** 2017-01-16 17:52 UTC

**Comment by CC-KRONUS** [comment] 2017-01-16 19:48
Thansk to you!

**Comment by dedmen** [comment] 2017-01-16 20:17
Pre release 188 just got released and contains the fix.
