### ISSUE TITLE
Compatibility issue with Exile

### ISSUE THREAD

**Issue by rbuddy101** [michail-nikolaev/task-force-arma-3-radio#1091] opened 2016-07-22 01:30 UTC
For some reason regardless of the version of TFR or CBA I use I am always told Task Force Radio is not loaded on my server and I get put in the TaskForceRadio teamspeak room for only a few seconds. My launch parameters are correct and have been triple checked.

**Comment by Nullfati** [comment] 2016-07-22 15:38
Same problem. TFAR have any debug logs?

**Comment by drawpause** [comment] 2016-07-22 17:00
I've been trying to get TFAR to work with Exile for months now, retrying after every update (TFAR, CBA, Exile and Arma). Exile's issues with CBA have been addressed in the recent version, but it's still the same – everyone gets booted off the TaskForceRadio channel after a few seconds.

Does the TFAR development team have any idea what the root of the problem is? Any info would be helpful, so we could let the Exile dev team know and possibly fix this issue.

**Comment by jokoho48** [comment] 2016-07-22 17:12
yes Exile Overwrite some Not Stackable Eventhandler for "Security Reasons" that break TFAR and CBA.

**Comment by drawpause** [comment] 2016-07-22 17:14
> yes Exile Overwrite some Not Stackable Eventhandler for "Security Reasons" that break TFAR and CBA.

AFAIK they have fixed that. At least you can enable the eventhandler thing in the server configs.

**Comment by Nullfati** [comment] 2016-07-22 21:09
> AFAIK they have fixed that. At least you can enable the eventhandler thing in the server configs.
@drawpause where its enable?

**Comment by rbuddy101** [comment] 2016-07-22 22:39
In the  @exile_server_config you can set "StackedEH" to 1 but even after doing that it still won't work.

**Comment by xeran** [comment] 2016-07-25 15:07
Same problem on my server put StackedEH on

**Comment by rbuddy101** [comment] 2016-07-25 22:10
At this point I am willing to pay someone to get it working because it has been a major inconvenience for my community.

**Comment by Nullfati** [comment] 2016-07-26 07:52
> At this point I am willing to pay someone to get it working because it has been a major inconvenience for my community.

Maybe you  post fix?

**Comment by ArMaTeC** [comment] 2016-07-26 08:23
cause of this is simple the preinit that runs the server side function fires to soon so to fix this you need to add [] spawn TFAR_fnc_TaskForceArrowheadRadioInit; to your server postinit files that are run after the server mission is loaded. this is only a work around as i feel bis have messed up there function preinit on a heavily modded server

**Comment by rbuddy101** [comment] 2016-07-26 21:09
so my PostInit is 

"/**
 * ExileServer_system_process_postInit
 *
 * Exile Mod
 * www.exilemod.com
 * © 2015 Exile Mod Team
 *
 * This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License. 
 * To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/4.0/.
 */
 
if (!isNil "PublicServerVersion") then
{
	call ExileClient_system_map_initialize;
	call ExileServer_system_thread_initialize;
	call ExileServer_system_playerSaveQueue_initialize;
	call ExileServer_system_swapOwnershipQueue_initialize;
	call ExileServer_system_vehicleSaveQueue_initialize;
	call ExileServer_system_simulationMonitor_initialize;
	call ExileServer_system_lootManager_initialize;
	call ExileServer_system_weather_initialize;
	call ExileServer_system_garbageCollector_cleanDatabase;
	call ExileServer_system_event_initialize;
	call ExileServer_world_initialize;
	call ExileServer_system_russianRoulette_initialize;
	PublicServerIsLoaded = true; 
	publicVariable "PublicServerIsLoaded";
	format ["Server is up and running! Version: %1", PublicServerVersion] call ExileServer_util_log;
	call ExileServer_system_garbageCollector_start;
	call ExileServer_system_rcon_event_ready;
};"

So where exactly do I put it in there @ArMaTeC

**Comment by rbuddy101** [comment] 2016-07-26 21:43
Where would i put it in here

"/**
 * Post-Initialization
 *
 * Exile Mod
 * www.exilemod.com
 * © 2015 Exile Mod Team
 *
 * This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License. 
 * To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/4.0/.
 */
 

call ExileServer_system_process_postInit;

true"

@ArMaTeC

**Comment by commy2** [comment] 2016-07-27 04:50
Work around for Exile bull shit can be found here:
https://github.com/CBATeam/CBA_A3/issues/400#issuecomment-228466041

**Comment by rbuddy101** [comment] 2016-07-27 09:41
[A3Log.txt](https://github.com/michail-nikolaev/task-force-arma-3-radio/files/385738/A3Log.txt)

@commy2 even after adding that trigger to my init in my mission file and doing what @ArMaTeC suggested TFR kicks me from the channel after a few seconds. I have tried multiple TFR versions with no luck. I attached my log to this post so maybe someone could find the error.

**Comment by jus61** [comment] 2016-09-02 10:58
Does anyone have a solution

**Comment by commy2** [comment] 2016-09-07 15:26
@jus61 
Exile is breaking other mods on purpose. That's why TFAR doesn't work with it. You'll have to bug the Exile devs about this. Good luck with that though. They are not very cooperative...

**Comment by jus61** [comment] 2016-09-08 06:25
thx

**Closed** 2016-09-16 11:55 UTC
