### ISSUE TITLE
CAPS stuck for some players

### ISSUE THREAD

**Issue by michail-nikolaev** [michail-nikolaev/task-force-arma-3-radio#817] opened 2014-10-22 20:50 UTC

**Comment by dedmen** [comment] 2016-09-19 07:16
Also occurs to some people on 0.9.8 Not very often though.

**Comment by dedmen** [comment] 2017-03-19 19:34
Can't reproduce. Letting CTRL go while still holding CAPS stops LR Transmission. Which was what I thought was not working in my last comment. Besides we didn't get any reports about this since 0.9.7 so... Closing this

**Closed by dedmen** 2017-03-19 19:34 UTC
Labels: bug
