### ISSUE TITLE
Speaking bug when remote controlling a unit in zeus

### ISSUE THREAD

**Issue by chris579** [michail-nikolaev/task-force-arma-3-radio#1275] opened 2017-06-11 18:37 UTC
**Arma 3 Version:** `1.70` (stable)
**CBA Version:** `3.3.1` (stable)
**Task Force Radio Version:** `0.9.12` (stable)

**Mods:**
- `@ACE 3`
- `@CBA_A3`
- `@task_force_radio`
- `A ton of other mods that shouldn't affect this issue`

**Description:**
- When speaking with a remote controlled unit in zeus the speaker origin is frequently swapped between the zeus unit and the remote controlled unit.
- This was only discovered when using a zeus slot in combination with a zeus module

**Steps to reproduce:**
- Get a buddy
- Create a small mission with a zeus slot and a zeus module owned by the zeus slot
- Create a slot for your buddy
- Start the mission
- Navigate with zeus to the left side of your buddy
- Place a unit in zeus and remote control it
- Go with the unit to the right side of your buddy
- Start speaking
- Your buddy should hear you speaking but with different sources, sometimes the zeus unit's position sometimes the remote controlled unit's position

**Where did the issue occur?**
- Multiplayer (No matter if dedicated or not)

**Comment by dedmen** [comment] 2017-06-12 12:42
Already fixed months ago in 1.0 branch. Atleast the Remote Controlling voice not working at all. Which was probably caused by the swapping

**Comment by chris579** [comment] 2017-06-25 23:37
Got some time today to reproduce and record this bug. Dunno if this is what you mean but [here](https://youtu.be/vLaUIc7HHKk) is a short clip with 2 scenes

**Comment by dedmen** [comment] 2017-06-26 06:15
As I said. Already fixed in 1.0. Mooooost likely.

**Closed** 2017-06-26 10:41 UTC
