### ISSUE TITLE
Multiple TS channels

### ISSUE THREAD

**Issue by alexcroox** [michail-nikolaev/task-force-arma-3-radio#1031] opened 2015-12-13 13:32 UTC
It would be great if when spawning instead of moving everyone to a single TS room the plugin could move you to a couple of different channels in TS (mission maker defined based on squad). That way if you play with public players without TFR, they don't hear 30 people talking over each other, but just 5-10 people max.

Not sure if it can even be done technically, but I know TS allows cross room comms with whisper systems so thought it might be worth asking :)

**Comment by rogerxxxx** [comment] 2015-12-13 16:07
There should be a  server.conf or tfar-server.conf file distributed with the map scenario packages, providing default frequencies based upon server administrators wishes.  The tfar-server.conf file having default frequencies, should be further broken into squads.  However, the opposing team players could possibly obtain their opposing team's frequencies quiet easily.

Due to digital displays for the past 10+ years, there should be an optional quoted string providing a description string for the frequency!  (ie. 100.1 "GND", 54.8 "AIR")

Shrugs. These are some examples within a little bit more readily typed configuration file, similar to Linux configuration files.

#opposition team - red team
#opposition team - blue squad
#opposition team - green squad
#opposition team - yellow squad

blue team red squad = 100.1, 54.8
# GROUND 100.1, AIR 54.8
#blue team - blue squad
#blue team - green squad
#blue team - yellow squad

**Comment by alexcroox** [comment] 2015-12-13 16:11
I'm not sure you understood the question. Channels as in teamspeak rooms. Not in-game frequencies.

**Comment by rogerxxxx** [comment] 2015-12-13 16:17
Oh, you mean to say separating players by squad within team speak to prevent chatter.

But if the TFAR server had had the above frequencies, the TFAR server end could export those defined variables to the team speak plugin?  I'm not sure if there is any bi-directional data being sent between TFAR and TeamSpeak though.

**Comment by alexcroox** [comment] 2015-12-13 16:20
Yer when we play public nights, move each squad into a different TS room. Then if a public player joins our TS, they don't have to hear everyone at the same time and can still get involved in the comms with us without us having to play without TFR entirely. Currently joining a big TFR TS room for someone without TFR is aids :D

**Comment by rogerxxxx** [comment] 2015-12-13 16:28
Oh.  I see that occur too.  ie. The other public player has trouble configuring TFAR, etc, or they cannot get TFAR working for what ever reason.  (And/or so the other player can interact with the default team frequency, for which doesn't occur as of yet that I know of.)

I understand the initial comment now.  If I'm not mistaken, the TFAR has to likely have a default frequency (ie. server.conf mentioned above.) to share with the other TeamSpeak group to prevent cross-talk.

**Comment by michail-nikolaev** [comment] 2015-12-13 21:31
Hm... But in your current scheme it is not possible to use cross-squad comms, right?

**Comment by alexcroox** [comment] 2015-12-14 03:31
Sorry I should have explained, we use whisper lists amongst squad leaders so they can communicate across the different rooms.

**Comment by dedmen** [comment] 2016-09-19 01:59
"That way if you play with public players without TFR, they don't hear 30 people talking over each other, but just 5-10 people max." 
So the issue is basically supporting to play with players that dont use TFAR?
As TFAR can be installed from the Steam workshop with just one click every player even on a public server should be able to easilly install it.

Possible solve for this is to allow the teamspeak plugin to communicate with people in other channels. Which is not possible. Because teamspeak 3D sound only works when you are in the same channel. You would need to move all players that are near eachother into one channel. And probably have whisperlists for each player depending on the radio frequencies they are on. This is way to complex and would harm functionality, immersion and performance.

So id suggest to close this issue as we wont implement that. @michail-nikolaev

**Comment by kavinsky** [comment] 2016-09-19 08:48
+1 to closing.

**Closed** 2016-10-12 15:50 UTC
Labels: question
